config/routes.rb
Rails.application.routes.draw do
  scope '/', controller: :home do
    get  :index
    post :new_session
    get  :sign_in
    get  :sign_out
  end

  resources :ip_addresses, except: [:index] do
    resource :virtual_machine, only: [:show, :destroy] do
      post :power_on
      post :power_off
    end
  end
  resource :virtual_machine, only: [:new, :create]

  namespace :ldap do
    resource :user, only: [:new, :create, :edit, :update]
  end

  namespace :admin do
    resources :local_records, except: :show
  end

  namespace :syskan do
    resources :users, only: :index do
      post :increment_vm_limit
      post :decrement_vm_limit
    end
    resources :virtual_machines, only: :index do
      post :toggle_cleanup_marked
    end
    resources :vlan51_ip_addresses, only: [:index, :new, :create, :destroy]
  end

  root to: 'home#index'

  get '*path', to: 'home#index'
end

app/models/local_record.rb
class LocalRecord < ActiveRecord::Base
  SourceHost    = 'urasoe.ie.u-ryukyu.ac.jp.'
  ContactEmail  = 'hostmaster.ie.u-ryukyu.ac.jp.'
  RefreshSecond = 8.hours.to_i
  RetrySecond   = 2.hours.to_i
  ExpireSecond  = 4.weeks.to_i
  MinTTLSecond  = 24.hours.to_i

  belongs_to :ip_address

  validates_presence_of  :rdtype, :ttl, :name
  validates_inclusion_of :rdtype, in: ['NS', 'SOA', 'PTR', 'CNAME', 'A', 'AAAA', 'MX', 'TXT']

  def soa_from_serial serial
    [SourceHost, ContactEmail, serial, RefreshSecond, RetrySecond,  ExpireSecond,  MinTTLSecond].map(&:to_s).join(' ')
  end

  def soa_record
    case self.rdtype
    when 'A'
      LocalRecord.where(name: ip_address.affiliation_detail.fqdn , rdtype: 'SOA').first
    when 'AAAA'
      LocalRecord.where(name: ip_address.affiliation_detail.fqdn , rdtype: 'SOA').first
    when 'PTR'
      if self.name.include?('addr')
        LocalRecord.where(name: (ip_address.rev4).split('.').drop(1).join('.'), rdtype: 'SOA').first
      elsif self.name.include?('ip6')
        LocalRecord.where(name: ip_address.affiliation_detail.rev6 , rdtype: 'SOA').first
      end
    else
      return nil
    end
  rescue ActiveRecord::RecordNotFound
    return nil
  end

  def update_serial
    return self.soa_record.try(:update_serial) unless self.rdtype == 'SOA'

    today_serial   = Time.now.strftime('%Y%m%d00')
    current_serial = self.rdata.split(' ').try(:[], 2)

    if current_serial.to_i >= today_serial.to_i
      self.rdata = soa_from_serial(current_serial.succ)
    else
      self.rdata = soa_from_serial(today_serial)
    end
    return self.save
  end
end

app/controllers/admin/local_records_controller.rb
class Admin::LocalRecordsController < ApplicationController
  before_action :authenticate_iesudoer!

  def index
    @records = LocalRecord.where(ip_address_id: nil).order(:name).order(:rdtype)
  end

  def new
    @record = LocalRecord.new
  end

  def create
    @record = LocalRecord.new(local_record_params)

    if @record.save
      redirect_to admin_local_records_path, notice: 'Create LocalRecord Successfully'
    else
      render :new
    end
  end

  def edit
    @record = LocalRecord.find params[:id]
  end

  def update
    @record = LocalRecord.find params[:id]

    if @record.update_attributes(local_record_params)
      redirect_to admin_local_records_path, notice: 'Update LocalRecord Successfully'
    else
      render :edit
    end
  end

  def destroy
    @record = LocalRecord.find params[:id]
    @record.destroy
    redirect_to admin_local_records_path, notice: 'Delete LocalRecord Successfully'
  end

  private

  def local_record_params
    params.require(:local_record).permit(:name, :rdtype, :rdata, :ttl)
  end
end

app/helpers/admin/local_records_helper.rb
module Admin::LocalRecordsHelper
end

app/views/admin/local_records/_form.html.haml
= form_for [:admin, @record] do |f|

  - if @record.errors.present?
    .alert.alert-warning
      %ul
        - @record.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label      :name
    = f.text_field :name
  .field
    = f.label      :rdtype
    = f.text_field :rdtype
  .field
    = f.label      :rdata
    = f.text_field :rdata
  .field
    = f.label      :ttl
    = f.text_field :ttl

  .actions
    = f.submit

app/views/admin/local_records/edit.html.haml
%h2 Edit LocalRecord

= render partial: 'form'

= button_to('Delete Local record', admin_local_record_path(@record), method: :delete, data: {confirm: 'Are you sure?'}, class: ['btn', 'btn-default', 'btn-danger'])

= link_to 'Back', admin_local_records_path

app/views/admin/local_records/index.html.haml
%h2 LocalRecords

= insert_alert

%table.table
  %tbody
    %tr
      %td name
      %td rdtype
      %td rdata
      %td ttl
    - @records.each do |record|
      %tr
        %td= link_to(record.name, edit_admin_local_record_path(record))
        %td= record.rdtype
        %td= record.rdata
        %td= record.ttl
    %tr
      %td
      %td
      %td
      %td= link_to('New Record', new_admin_local_record_path)

app/views/admin/local_records/new.html.haml
%h2 New Local Record

= render partial: 'form'