config/routes.rb
Rails.application.routes.draw do
  scope '/', controller: :home do
    get  :index
    post :new_session
    get  :sign_in
    get  :sign_out
  end

  resources :ip_addresses, except: [:index] do
    resource :virtual_machine, only: [:show, :destroy] do
      post :power_on
      post :power_off
    end
  end
  resource :virtual_machine, only: [:new, :create]

  namespace :ldap do
    resource :user, only: [:new, :create, :edit, :update]
  end

  namespace :admin do
    resources :local_records, except: :show
  end

  namespace :syskan do
    resources :users, only: :index do
      post :increment_vm_limit
      post :decrement_vm_limit
    end
    resources :virtual_machines, only: :index do
      post :toggle_cleanup_marked
    end
    resources :vlan51_ip_addresses, only: [:index, :new, :create, :destroy]
  end

  root to: 'home#index'

  get '*path', to: 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!,  only: [:sign_in, :new_session]

  def index
    all_ips           = current_user.ip_addresses.includes(:virtual_machine)
    @ip_addresses     = all_ips.select{|s| s.virtual_machine.blank?}
    @virtual_machines = all_ips - @ip_addresses
  end

  def new_session
    user = LDAP::User.find(sign_in_params[:uid])

    unless user.bind(sign_in_params[:password])
      sign_out_user
      raise 'ログインに失敗しました。uidかパスワードが間違っています。'
    end

    if user.graduate?
      sign_out_user
      raise '卒業生はログインできません。'
    end

    sign_in_user(sign_in_params[:uid])
    redirect_to root_path, notice: 'ログインに成功しました。'
  rescue ActiveLdap::AuthenticationError => e
    redirect_to sign_in_path, alert: 'ログインに失敗しました。uidかパスワードが間違っています。'
  rescue => e
    redirect_to sign_in_path, alert: e.message
  end

  def sign_in
  end

  def sign_out
    sign_out_user
    redirect_to sign_in_path, notice: 'ログアウトしました。'
  end

  private

  def sign_in_params
    params.permit(:uid, :password)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
= insert_alert

%h2 IP Addresses

%table.table
  %tbody
    %tr
      %td domain
      %td IPv4 address
      %td IPv6 address
      %td mac address
    - @ip_addresses.each do |ip|
      %tr
        %td= link_to(ip.fqdn, ip_address_path(ip))
        %td= ip.ipv4
        %td= ip.ipv6
        %td= ip.mac_address
    %tr
      %td
      %td
      %td
      %td= link_to('New IP', new_ip_address_path)

- if current_user.vm_controllable? || current_user.vm_creatable?
  %h2 Virtual Machines
  %table.table
    %tbody
      %tr
        %td domain
        %td IPv4 address
        %td IPv6 address
        %td mac address
        %td Details
      - @virtual_machines.each do |ip|
        %tr
          %td= ip.fqdn
          %td= ip.ipv4
          %td= ip.ipv6
          %td= ip.mac_address
          %td= link_to 'Detail', ip_address_virtual_machine_path(ip)
      %tr
        %td
        %td
        %td
        %td
        %td= current_user.vm_creatable? ? link_to('New VM', new_virtual_machine_path) : ''

app/views/home/sign_in.html.haml
%h2 Sign in

= insert_alert

= form_tag new_session_path, method: :post do
  .field
    = label_tag      :uid
    = text_field_tag :uid, nil, autofocus: true
  .field
    = label_tag          :password
    = password_field_tag :password, nil, autocomplete: 'off'
  .actions
    = submit_tag 'Sign in'