config/routes.rb
Rails.application.routes.draw do
  scope '/', controller: :home do
    get  :index
    post :new_session
    get  :sign_in
    get  :sign_out
  end

  resources :ip_addresses, except: [:index] do
    resource :virtual_machine, only: [:show, :destroy] do
      post :power_on
      post :power_off
    end
  end
  resource :virtual_machine, only: [:new, :create]

  namespace :ldap do
    resource :user, only: [:new, :create, :edit, :update]
  end

  namespace :admin do
    resources :local_records, except: :show
  end

  namespace :syskan do
    resources :users, only: :index do
      post :increment_vm_limit
      post :decrement_vm_limit
    end
    resources :virtual_machines, only: :index do
      post :toggle_cleanup_marked
    end
    resources :vlan51_ip_addresses, only: [:index, :new, :create, :destroy]
  end

  root to: 'home#index'

  get '*path', to: 'home#index'
end

app/models/virtual_machine.rb
class VirtualMachine < ActiveRecord::Base
  belongs_to :ip_address

  validates_presence_of   :name, :kvm_hostname
  validates_uniqueness_of :name

  def save_from_submit_form submit_params
    if IEConfig::KVM.templates.find{|s| s == submit_params[:template_name]}.blank?
      errors.add(:template_name, 'template missing') and return false
    end

    user       = User.find(submit_params[:user_id])
    ip         = user.ip_addresses.new(affiliation: submit_params[:affiliation],
                                       domain:      submit_params[:domain], mac_address: random_mac)

    unless ip.save_with_auto_assign
      errors.add(:ip_address, ip.errors.full_messages.join("\n")) and return false
    end
    self.ip_address = ip
    self.update_attributes!(name: vm_name, kvm_hostname: IEConfig::KVM.not_busy_hostname,
                            template_name: submit_params[:template_name])
    vm_create
    self.ip_address.update_attributes!(mac_address: vm_control.nics.first.mac)

    return true
  rescue => e
    ip_address.try(:destroy)
    errors.add(:vm, e.message) and return false
  end

  def archive
    vm_control.volumes.each do |v|
      v.clone_volume(v.name, IEConfig::KVM::ArchivePoolName)
      v.destroy
    end
  end

  def vm_name
    return nil if ip_address.blank?
    [ ip_address.try(:user).try(:uid),
     '(', ip_address.domain, '.', ip_address.affiliation, ')'].join
  end

  def volume_name
    [self.vm_name, IEConfig::KVM::Format].join('.')
  end

  def information
    vm = vm_control
    {
      cpus: vm.cpus,
      memory_size: vm.max_memory_size,
      volume_size: vm.volumes.first.capacity,
      is_active: vm.active?
    }
  end

  def power_on
    vm_control.start
  end

  def power_off
    vm_control.halt
  end

  def active?
    vm_control.active?
  end

  private

  def vm_control
    kvm = IEConfig::KVM.connection(kvm_hostname)
    kvm.servers.find{|s| s.name == self.name}
  end

  def vm_create
    kvm        = IEConfig::KVM.connection(kvm_hostname)
    vol        = kvm.volumes.find{|s| s.name == template_name}
    cloned_vol = vol.clone_volume(volume_name, IEConfig::KVM::PoolName)
    server     = kvm.servers.create(name: vm_name, volumes: [cloned_vol],
                                    nics: [{bridge: IEConfig::KVM::FlatBridge, model: IEConfig::KVM::BridgeModel}],
                                    memory_size: IEConfig::KVM::DefaultMemorySize)
  end

  def vm_delete
    vm = vm_control
    vm.try(:volumes).try(:each, &:destroy)
    vm.try(:destroy)
  end

  def random_mac
    random_mac = 6.times.map{format '%02x', (0..255).to_a.sample}.join(':') # FIXME: improve
  end
end

app/controllers/syskan/virtual_machines_controller.rb
class Syskan::VirtualMachinesController < ApplicationController
  before_action :authenticate_syskan!

  def index
    @virtual_machines = VirtualMachine.order(:created_at)
  end

  def toggle_cleanup_marked
    vm = VirtualMachine.find params[:virtual_machine_id]
    vm.cleanup_marked = !vm.cleanup_marked

    if vm.save
      redirect_to syskan_virtual_machines_path
    else
      redirect_to syskan_virtual_machines_path, alert: user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/virtual_machines_controller.rb
class VirtualMachinesController < ApplicationController
  before_action :check_vm_permission,  only:   [:new, :create]
  before_action :find_virtual_machine, except: [:new, :create]

  def new
  end

  def create
    @virtual_machine = VirtualMachine.new

    if @virtual_machine.save_from_submit_form(virtual_machine_params)
      current_user.update_attributes(vm_limit: current_user.vm_limit.pred)
      IpAddressMailer.notify_to_user(current_user, request.ip, :create, @virtual_machine.ip_address).deliver_now
      redirect_to root_path, notice: 'VMを作成しました'
    else
      render :new
    end
  end

  def show
    @vm_information  = @virtual_machine.information
  end

  def power_on
    @virtual_machine.power_on unless @virtual_machine.active?
    redirect_to ip_address_virtual_machine_path(@virtual_machine.ip_address)
  end

  def power_off
    @virtual_machine.power_off if @virtual_machine.active?
    redirect_to ip_address_virtual_machine_path(@virtual_machine.ip_address)
  end

  private

  def check_vm_permission
    redirect_to root_path unless current_user.vm_creatable?
  end

  def find_virtual_machine
    @virtual_machine = current_user.ip_addresses.find(params[:ip_address_id]).virtual_machine
  end

  def virtual_machine_params
    params.require(:virtual_machine).permit(:domain, :affiliation, :template_name).merge(user_id:current_user.id)
  end
end

app/helpers/virtual_machines_helper.rb
module VirtualMachinesHelper
end

app/views/virtual_machines/new.html.haml
%h2 New Virtual Machine

= insert_model_alert @virtual_machine

= form_tag(virtual_machine_path, action: :create, method: :post) do
  .field
    = label_tag      :domain
    = text_field_tag 'virtual_machine[domain]'

  .field
    = label_tag  :affiliation
    = select_tag 'virtual_machine[affiliation]',   options_for_select(IEConfig::Domain::Affiliations.map(&:to_option))

  .field
    = label_tag  :template_name
    = select_tag 'virtual_machine[template_name]', options_for_select(IEConfig::KVM.templates_for_options)

  = submit_tag

app/views/virtual_machines/show.html.haml
%h2= @virtual_machine.ip_address.fqdn

%table.table
  %tbody
    %tr
      %td IPv4
      %td= @virtual_machine.ip_address.ipv4
    %tr
      %td IPv6
      %td= @virtual_machine.ip_address.ipv6
    %tr
      %td Mac Address
      %td= @virtual_machine.ip_address.mac_address
    %tr
      %td CPU Core
      %td= @vm_information[:cpus]
    %tr
      %td Memory Size
      %td= @vm_information[:memory_size].kilobyte.to_s(:human_size)
    %tr
      %td Storage Size
      %td= "#{@vm_information[:volume_size]}GB"
    %tr
      %td Status
      %td= @vm_information[:is_active] ? 'Active' : 'Inactive'


- if @vm_information[:is_active]
  = button_to 'PowerOff', power_off_ip_address_virtual_machine_path, method: :post
- else
  = button_to 'PowerOn',  power_on_ip_address_virtual_machine_path,  method: :post