config/routes.rb
Rails.application.routes.draw do
  scope '/', controller: :home do
    get  :index
    post :new_session
    get  :sign_in
    get  :sign_out
  end

  resources :ip_addresses, except: [:index] do
    resource :virtual_machine, only: [:show, :destroy] do
      post :power_on
      post :power_off
    end
  end
  resource :virtual_machine, only: [:new, :create]

  namespace :ldap do
    resource :user, only: [:new, :create, :edit, :update]
  end

  namespace :admin do
    resources :local_records, except: :show
  end

  namespace :syskan do
    resources :users, only: :index do
      post :increment_vm_limit
      post :decrement_vm_limit
    end
    resources :virtual_machines, only: :index do
      post :toggle_cleanup_marked
    end
    resources :vlan51_ip_addresses, only: [:index, :new, :create, :destroy]
  end

  root to: 'home#index'

  get '*path', to: 'home#index'
end

app/views/layouts/_iesudoer_navbar.html.haml
%li.dropdown#iesudoer_dropdown
  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    管理者メニュー
    %span.caret
  %ul.dropdown-menu
    %li
      = link_to 'Create New LDAP User', new_ldap_user_path
    %li
      = link_to 'Manage LocalRecords',  admin_local_records_path

app/views/layouts/_syskan_navbar.html.haml
%li.dropdown#syskan_dropdown
  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
    syskan
    %span.caret
  %ul.dropdown-menu
    %li= link_to 'VM Permissions', syskan_users_path
    %li= link_to 'VM List',        syskan_virtual_machines_path
    %li= link_to 'VLAN51 Control', syskan_vlan51_ip_addresses_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Akatsuki
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{href: root_path} Akatsuki

        .collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if syskan_signed_in?
              = render partial: 'layouts/syskan_navbar'
            - if iesudoer_signed_in?
              = render partial: 'layouts/iesudoer_navbar'
            - if user_signed_in?
              %li= link_to 'LDAP情報変更', edit_ldap_user_path
              %li= link_to 'ログアウト', sign_out_path
            - else
              %li= link_to 'ログイン', sign_in_path

  = yield